######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 27 20:44:39 2011
######################################################################

QT -= gui
QT += network
TEMPLATE = app
QMAKE_CXXFLAGS += -std=gnu++0x

win32 {
    CONFIG += console
}

MOC_DIR = mocs
OBJECTS_DIR = obj

HEADERS  = *.h
SOURCES  = *cpp
